export const characters = [
  {
    id: "otec",
    name: "Отец",
    language: "ru",
    role: "Владелец бара",
    action: "otec-bar",
    avatar: "references/charakters/otec/avatar.png",
    scene: "references/charakters/otec/scene.png",
    focus: "50% 30%",
  },
  {
    id: "shkolnik",
    name: "Школьник",
    language: "ru",
    role: "Гость",
    game: "анекдоты",
    action: "shkolnik-jokes",
    avatar: "references/charakters/shkolnik/avatar.png",
    scene: "references/charakters/shkolnik/scene.png",
    focus: "50% 26%",
  },
  {
    id: "vlados",
    name: "Владос",
    language: "be",
    role: "Гость",
    action: "vlados-drink",
    avatar: "references/charakters/vlados/avatar.png",
    scene: "references/charakters/vlados/scene.png",
    focus: "50% 28%",
  },
  {
    id: "malyshka",
    name: "Малышка",
    language: "be",
    role: "Гость",
    action: "malyshka-borrow",
    avatar: "references/charakters/malyshka/avatar.png",
    scene: "references/charakters/malyshka/scene.png",
    focus: "62% 35%",
  },
  {
    id: "vital",
    name: "Віталь",
    language: "be",
    role: "Гость",
    avatar: "references/charakters/vital/avatar.png",
    focus: "45% 30%",
  },
  {
    id: "diana",
    name: "Диана",
    language: "ru",
    role: "Гость",
    game: "Файтинг",
    action: "diana-fight",
    avatar: "references/charakters/diana/avatar.png",
    scene: "references/charakters/diana/scene.png",
    focus: "45% 25%",
  },
  {
    id: "ben",
    name: "Бен",
    language: "ru",
    role: "Повар",
    game: "Закуска",
    action: "ben-cook",
    avatar: "references/charakters/ben/avatar.png",
    scene: "references/charakters/ben/scene.png",
    focus: "50% 20%",
  },
];

export function getCharacter(id) {
  return characters.find((c) => c.id === id) || null;
}
