export const characters = [
  {
    id: "otec",
    name: "Отец",
    language: "ru",
    role: "Владелец бара",
    action: "otec-bar",
    portrait: "references/charakters/otec/image.png",
    focus: "50% 30%",
  },
  {
    id: "shkolnik",
    name: "Школьник",
    language: "ru",
    role: "Гость",
    game: "анекдоты",
    action: "shkolnik-jokes",
    portrait: "references/charakters/shkolnik/scene.png",
    focus: "50% 26%",
  },
  {
    id: "vlados",
    name: "Владос",
    language: "be",
    role: "Гость",
    action: "vlados-drink",
    portrait: "references/charakters/vlados/scene2.png",
    focus: "50% 28%",
  },
  {
    id: "malyshka",
    name: "Малышка",
    language: "be",
    role: "Гость",
    action: "malyshka-borrow",
    portrait: "references/charakters/malyshka/577c619e-2e92-4477-b6bc-aad384c1c94c.png",
    focus: "62% 35%",
  },
  {
    id: "vital",
    name: "Віталь",
    language: "be",
    role: "Гость",
    portrait: "references/charakters/vital/28ea3a6c-3185-46f1-9f4b-1daafe16f0b3.png",
    focus: "45% 30%",
  },
  {
    id: "diana",
    name: "Диана",
    language: "ru",
    role: "Гость",
    game: "Файтинг",
    portrait: "references/charakters/diana/fb0f12d2-d23d-456c-b87b-7864ba46461d.png",
    focus: "45% 25%",
  },
  {
    id: "ben",
    name: "Бен",
    language: "ru",
    role: "Повар",
    game: "Закуска",
    action: "ben-cook",
    portrait: "references/charakters/ben/ecad18a2-d9d3-41d3-922c-346ade0f7362.png",
    focus: "50% 20%",
  },
];

export function getCharacter(id) {
  return characters.find((c) => c.id === id) || null;
}
